# Copyright (c) 2024-2026 AURa Project (Cbetts1/Damn-it-xm). All rights reserved.
# SPDX-License-Identifier: MIT
"""AURa Builder — code and config template generators."""

from __future__ import annotations

import json
from typing import Optional

from aura.utils import get_logger

_logger = get_logger("aura.builder.templates")

_MIT_HEADER = """\
# Copyright (c) 2024-2026 AURa Project (Cbetts1/Damn-it-xm). All rights reserved.
# SPDX-License-Identifier: MIT"""


class ModuleTemplate:
    """Generates a skeleton Python module with MIT header and a class stub."""

    def __init__(
        self,
        name: str,
        description: str = "",
        author: str = "AURa Builder",
    ) -> None:
        self.name = name
        self.description = description or f"AURa module: {name}"
        self.author = author

    def render(self) -> str:
        class_name = "".join(part.capitalize() for part in self.name.replace("-", "_").split("_"))
        return (
            f"{_MIT_HEADER}\n"
            f'"""{self.description}"""\n'
            "\n"
            "from __future__ import annotations\n"
            "\n"
            "import threading\n"
            "\n"
            "from aura.utils import get_logger, generate_id, utcnow\n"
            "\n"
            f'_logger = get_logger("aura.{self.name}")\n'
            "\n"
            "\n"
            f"class {class_name}:\n"
            f'    """Auto-generated by AURa Builder ({self.author})."""\n'
            "\n"
            "    def __init__(self) -> None:\n"
            "        self._lock = threading.RLock()\n"
            f'        _logger.info("{class_name}: initialised")\n'
            "\n"
            "    def metrics(self) -> dict:\n"
            "        return {}\n"
        )


class ScriptTemplate:
    """Generates a POSIX shell script with shebang and MIT header."""

    def __init__(self, name: str, description: str = "") -> None:
        self.name = name
        self.description = description or f"AURa script: {name}"

    def render(self) -> str:
        return (
            "#!/usr/bin/env sh\n"
            "# Copyright (c) 2024-2026 AURa Project (Cbetts1/Damn-it-xm). All rights reserved.\n"
            "# SPDX-License-Identifier: MIT\n"
            f"# {self.description}\n"
            "set -eu\n"
            "\n"
            f'echo "[{self.name}] starting..."\n'
            "\n"
            "# --- add implementation below ---\n"
            "\n"
            f'echo "[{self.name}] done."\n'
        )


class ConfigTemplate:
    """Generates a JSON configuration file."""

    def __init__(self, name: str, defaults: Optional[dict] = None) -> None:
        self.name = name
        self.defaults = defaults or {}

    def render(self) -> str:
        config: dict = {
            "name": self.name,
            "version": "1.0.0",
        }
        config.update(self.defaults)
        return json.dumps(config, indent=2)
